

spring:
  datasource:
#    username: root
#    password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost:3306/cryptomind?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:96guq34U8pTeNaq.root}
    password: ${DB_PASSWORD}
    # Đã thay localhost thành domain TiDB, port 4000, và sửa tham số SSL
    url: ${DB_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/cryptomind?sslMode=VERIFY_IDENTITY&serverTimezone=Asia/Ho_Chi_Minh}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: calm-ocelot-179749.upstash.io
      port: 6379
      username: default
      password: gQAAAAAAAr4lAAIgcDFmYTQxZDI5MjUzMTM0Zjg5OGNmM2RjMTUxYWU2NjU3OA
      timeout: 60000
      ssl: 
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  # <--- Thay email của bạn vào đây
    password: ${MAIL_PASSWORD}
    # <--- Paste 16 ký tự App Password vào đây (KHÔNG phải pass đăng nhập)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          # Thêm dòng này để timeout nếu mạng lag
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  ai:
    openai:
      api-key: ${GROQ_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: openai/gpt-oss-20b
  #gemini-3-flash-preview
  #gemini-2.5-flash-lite
  #gemini-2.5-flash
  rabbitmq:
    host: armadillo-01.rmq.cloudamqp.com
    port: 5671             # Thường là 5671 khi chạy CloudAMQP (hoặc 5672 nếu họ cho phép non-SSL)
    username: fpfwtvqk
    password: qxnre3qq8JjTmKowFjHNxmVdxnoTSMW2 # Đừng quên điền mật khẩu nhé
    virtual-host: fpfwtvqk       # Thường trên CloudAMQP vhost có tên giống username
    ssl:
      enabled: true              # Bật nếu dùng port 5671 (AMQPS)

    # Cấu hình cho phía Gửi (Producer)
    template:
      retry:
        enabled: true      # Tự động gửi lại nếu gặp lỗi mạng
        initial-interval: 2000ms
        max-attempts: 3    # Thử lại tối đa 3 lần

    # Cấu hình cho phía Nhận (Consumer/Worker)
    listener:
      simple:
        acknowledge-mode: auto      # Tự động xác nhận đã nhận tin khi xử lý xong
        concurrency: 2              # Số lượng "công nhân" chạy song song tối thiểu
        max-concurrency: 5          # Số lượng "công nhân" tối đa khi hàng đợi bị quá tải
        prefetch: 1                 # Mỗi công nhân chỉ

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

api:
  prefix: /api

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: ${JWT_EXPIRED_ACCESS}
  refresh-token-expiration: ${JWT_EXPIRED_REFRESH}
sepay:
  api-key: api11012004


ai:
  service:
    url: http://localhost:8000

app:
  crypto:
    aes-key: NJxOEWPWlsYbXsDuFfxtCSwzKZkjGL1G

google:
  client-id: ${GOOGLE_CLIENT_ID}
#logging:
#  level:
#    org:
#      hibernate:
#        # Log câu lệnh SQL (Bạn đã thấy rồi)
#        SQL: DEBUG
#        # HIỆN GIÁ TRỊ TRUYỀN VÀO DẤU ? (Để biết đang tìm User nào)
#        orm:
#          results: TRACE
#        # HIỆN CHI TIẾT THAM SỐ (Binding parameters)
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#    # Log cho Spring Scheduling (Nếu nghi ngờ do Task ngầm)
#    org.springframework.scheduling: DEBUG
