

spring:
  datasource:
    username: root
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/cryptomind?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1

    consumer:
      group-id: stock-trading-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}  # <--- Thay email của bạn vào đây
    password: ${MAIL_PASSWORD}
    # <--- Paste 16 ký tự App Password vào đây (KHÔNG phải pass đăng nhập)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          # Thêm dòng này để timeout nếu mạng lag
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  ai:
    openai:
      api-key: {GROQ_KEY} #${GEMINI_KEY}
      base-url: https://api.groq.com/openai #https://generativelanguage.googleapis.com
      chat:
        #completions-path: /v1beta/openai/chat/completions groq không cần
        options:
          model: llama-3.1-8b-instant #gemini-2.5-pro
          temperature: 0.7
#gemini-3-flash-preview
#gemini-2.5-flash-lite
#gemini-2.5-flash
server:
  port: 8080

api:
  prefix: /api

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: ${JWT_EXPIRED_ACCESS}
  refresh-token-expiration: ${JWT_EXPIRED_REFRESH}
sepay:
  api-key: api11012004


ai:
  service:
    url: http://127.0.0.1:8000

app:
  crypto:
    aes-key: NJxOEWPWlsYbXsDuFfxtCSwzKZkjGL1G

#logging:
#  level:
#    org:
#      hibernate:
#        # Log câu lệnh SQL (Bạn đã thấy rồi)
#        SQL: DEBUG
#        # HIỆN GIÁ TRỊ TRUYỀN VÀO DẤU ? (Để biết đang tìm User nào)
#        orm:
#          results: TRACE
#        # HIỆN CHI TIẾT THAM SỐ (Binding parameters)
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#    # Log cho Spring Scheduling (Nếu nghi ngờ do Task ngầm)
#    org.springframework.scheduling: DEBUG